// using System;


// namespace RegentHealthBookingSystem
// {
//     class DeletePatientByIndex
//     {
//         // Este método se encarga de mostrar a todos los pacientes con su índice para que el usuario pueda elegir cuál eliminar
//         public void ShowAllPatientsWithIndex()
//         {
//             for (int i = 0; i < patients.Count; i++)
//             {
//                 Console.WriteLine($"{i + 1}) {patients[i].FullName} | Date: {patients[i].AppointmentDate} | Type: {patients[i].AppointmentType} | Price: ${patients[i].AppointmentPrice}");
//             }
//             Console.WriteLine("Which one do you want to delete? Say by the index.");
//         }
//     }   
// }